# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1903e67d817bd5e73d77747939f5de89ad5effcc79a8f33fc977e6d15bdebcffd47072e2d435c7f2d1cf8a21c9d9efd417fcd589ea2581677bc38dd99c753a8b

test:
  secret_key_base: c679431986b2561e71f0f94a561fe2bf88d977d6e17661de3bc4a403bf4a0114ff204fdb040cbd598107f619b13f9fcf7b7026eba408ff83b22cb050a02d8652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
